#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/sbin/mentohust

get_config() {
	config_load mentohust
	config_get enable config enable 0
	config_get username config username
	config_get password config password
	config_get interface config interface
	config_get ipaddr config ipaddr 0.0.0.0
	config_get gateway config gateway 0.0.0.0
	config_get mask config mask 255.255.255.0
	config_get dns config dns 0.0.0.0
	config_get ping config ping 0.0.0.0
	config_get timeout config timeout 8
	config_get interval config interval 30
	config_get wait config wait 15
	config_get fail_number config fail_number 0
	config_get multicast_address config multicast_address 1
	config_get dhcp_mode config dhcp_mode 1
	config_get dhcp_script config dhcp_script "udhcpc -i"
	config_get version config version 0.00
	config_get data_file config data_file

	if [ "$dhcp_mode" != "0" ] && [ -n "$interface" ]; then
		case "$dhcp_script" in
			"udhcpc -i"|*" -i")
				dhcp_script="$dhcp_script $interface"
			;;
		esac
	fi
}

append_opt() {
	local opt="$1"
	local val="$2"

	[ -n "$val" ] && procd_append_param command "-${opt}${val}"
}

start_service() {
	get_config

	[ "$enable" = "1" ] || return 0
	[ -x "$PROG" ] || return 1
	[ -n "$username" ] || return 1
	[ -n "$password" ] || return 1
	[ -n "$interface" ] || return 1

	procd_open_instance mentohust
	procd_set_param command "$PROG"
	append_opt u "$username"
	append_opt p "$password"
	append_opt n "$interface"
	append_opt i "$ipaddr"
	append_opt m "$mask"
	append_opt g "$gateway"
	append_opt s "$dns"
	append_opt o "$ping"
	append_opt t "$timeout"
	append_opt e "$interval"
	append_opt r "$wait"
	append_opt l "$fail_number"
	append_opt a "$multicast_address"
	append_opt d "$dhcp_mode"
	append_opt b 0
	append_opt v "$version"
	append_opt f "$data_file"
	append_opt c "$dhcp_script"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger mentohust
}

reload_service() {
	stop
	start
}

stop_service() {
	local pids

	pids="$(pgrep -f "^$PROG")"
	[ -n "$pids" ] && kill $pids >/dev/null 2>&1
}
